---
database_file: "<%= ENV.fetch('HOME') %>/.local/timetrap/timetrap.db"
round_in_seconds: 900
append_notes_delimiter: " "
formatter_search_paths:
- "<%= ENV.fetch('HOME') %>/.config/timetrap/formatters"
default_formatter: text
auto_sheet: environment
auto_sheet_search_paths:
- "<%= ENV.fetch('HOME') %>/.config/timetrap/auto_sheets"
default_command: today
auto_checkout: false
require_note: false
note_editor: false
week_start: Monday
