#!/usr/bin/env bash

set -euo pipefail

main() {
	local commit="${1}"

	if ! grep -qE '^(feat|fix|docs|style|ref|perf|test|chore)\(.+\):' "${commit}"; then
		echo "Commmit subject formatted incorrectly." 1>&2
		return 1
	fi

	if grep -qE '^(feat|fix|docs|style|ref|perf|test|chore)\(.+\):\s[A-Z]' "${commit}"; then
		echo "Subject cannot start with a capital." 1>&2
		return 1
	fi
}

main "$@"
