#!/usr/bin/env bash

set -euo pipefail

lint_editorconfig() {
	if [ ! -f .editorconfig ]; then
		return 0
	fi

	declare uncovered_files=0
	declare ignore_file="$(mktemp)"

	cat << EOF > "${ignore_file}"
.editorconfig
.editorconfigignore
.gitmodules
.gitattributes
.gitignore
EOF

	if [ -f .editorconfigignore ]; then
		cat .editorconfigignore >> "${ignore_file}"
	fi

	# Check files in the commit excluding those ignored
	while read -r file; do
		if [ -z "$(editorconfig "${PWD}/${file}" 2>/dev/null)" ]; then
			echo "${file}"
			((++uncovered_files))
		fi
	done < <(comm -23 <(git diff --cached --name-only --diff-filter=ACM | sort) <(sort "${ignore_file}"))

	if [ $uncovered_files -ne 0 ]; then
		echo "${uncovered_files} uncovered file(s) by editorconfig rules"
		return 1
	else
		return 0
	fi
}

lint_spelling() {
	local counter=0;

	local ignore_file spell_file lint_files

	spell_file="$(git config --type path --get dotfiles.spellfile)"

	if [ -z "${spell_file}" ]; then
		return 0
	fi

	ignore_file="$(git config --type path --default .spellignore --get dotfiles.spellexcludesfile)"

	if [ -f "${ignore_file}" ]; then
		lint_files="$(comm -23 <(git ls-files) "${ignore_file}")"
	else
		lint_files="$(git ls-files)"
	fi

	local -a args=( )
	while read -r file; do
		args+=( "${file}" )
	done <<< "${lint_files}"

	if git grep -iF --line-number -f "${spell_file}" "${args[@]}"; then
		echo
		echo 'Lame spelling mistakes found.'
		return 1
	else
		return 0
	fi
}

check_pgp_key() {
	if ! gpg --card-status &> /dev/null; then
		echo "No smart card found. Is the Yubikey plugged in?"
		return 1
	else
		return 0
	fi
}

run_local_hooks() {
	local project_hook=".git/hooks/$(basename "${0}")"

	if [ -f "${project_hook}" ]; then
		"${project_hook}" "$@"
	fi
}

main() {
	lint_editorconfig
	lint_spelling
	check_pgp_key
	run_local_hooks "$@"
}

main "$@"
