#!/usr/bin/env bash

set -euo pipefail

check_pgp_key() {
	if ! gpg2 --card-status &> /dev/null; then
		echo "No smart card found. Is the Yubikey plugged in?"
		return 1
	else
		return 0
	fi
}

run_local_hooks() {
	local project_hook_dir=".git/hooks/$(basename "${0}")"

	if [ -d "${project_hook_dir}" ]; then
		while read -r hook; do
			"${hook}" "$@"
		done < <(find "${project_hook_dir}" -type f)
	fi
}

main() {
	check_pgp_key
	run_local_hooks "$@"
}

main "$@"
