#!/usr/bin/env bash

set -euo pipefail

lint_editorconfig() {
	if [ ! -f .editorconfig ]; then
		return 0
	fi

	declare uncovered_files=0
	declare ignore_file="$(mktemp)"

	cat << EOF > "${ignore_file}"
.editorconfig
.editorconfigignore
.gitmodules
.gitattributes
EOF

	if [ -f .editorconfigignore ]; then
		cat .editorconfigignore >> "${ignore_file}"
	fi

	# Check files in the commit excluding those ignored
	while read -r file; do
		if [ -z "$(editorconfig "${PWD}/${file}" 2>/dev/null)" ]; then
			echo "${file}"
			((++uncovered_files))
		fi
	done < <(comm -23 <(git diff --cached --name-only --diff-filter=ACM | sort) <(sort "${ignore_file}"))

	if [ $uncovered_files -ne 0 ]; then
		echo "${uncovered_files} uncovered file(s) by editorconfig rules"
		return 1
	else
		return 0
	fi
}

check_pgp_key() {
	if ! gpg2 --card-status &> /dev/null; then
		echo "No smart card found. Is the Yubikey plugged in?"
		return 1
	else
		return 0
	fi
}

run_local_hooks() {
	local project_hook=".git/hooks/$(basename "${0}")"

	if [ -f "${project_hook}" ]; then
		"${project_hook}" "$@"
	fi
}

main() {
	# lint_editorconfig
	check_pgp_key
	run_local_hooks "$@"
}

main "$@"
