set -U fish_user_abbreviations \
    'be=bundle exec' \
    'ber=bundle exec rake' \
    'berc=bundle exec rails c' \
    'berg=bundle exec rails g' \
    'berup=bundle exec rackup' \
    'bi=bundle install' \
    'bp=bundle pack' \
    'bu=bundle update' \
    'tf=tail -f' \
    'g=git' \
    'ga=git add' \
    'gaa=git add -A' \
    'gp=git pull' \
    'gs=git status' \
    'gb=git branch' \
    'gco=git checkout' \
    'gcb=git checkout -b' \
    'gs=git status -sb' \
    'gh=git head' \
    'gl=git l' \
    'gll=git ll' \
    'gd=git diff' \
    'gdc=git diff --cached' \
    'gdw=git diff --color-words' \
    'gds=git diff --stat' \
    'gc=git commit -v' \
    'gca=git commit -v -a' \
    'gcm=git commit -m' \
    'gf=git fetch' \
    'gfa=git fetch --all' \
    'gm=git merge' \
    'gr=git rebase' \
    'gcp=git cherry-pick'
